##
##  Makefile -- Build procedure for sample mod_foo Apache module
##  Autogenerated via ``apxs -n mod_foo -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
CXX=g++
CXXFLAGS=-std=c++14 
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib
LIBS=-lstdc++

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_datanoesis.o mod_datanoesis.lo mod_datanoesis.slo mod_datanoesis.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/datanoesis

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

